
default_platform(:ios)

platform :ios do
  desc 'Build Project and execute test case'
  lane :unit_test do | options |
    scan(
      clean: options[:clean],
      skip_package_dependencies_resolution: options[:skip_package_dependencies_resolution]
    )
    end
end
